- name: phd-assess secrets
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ secret_name }}"
      namespace: "{{ openshift_namespace }}"
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
   _data: |
        "{{ encryption_key_name }}": "{{ lookup('file', '/keybase/team/'+ keybase_secrets_folder + '/PHDASSESS_ENCRYPTION_KEY') | b64encode }}"

- name: phd-assess meteor secrets
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ meteor_secret_name }}"
      namespace: "{{ openshift_namespace }}"
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
    _data: |
      "{{ websrv_password_key_name }}": "{{ lookup('file', '/keybase/team/epfl_phdassess/WEBSRV_PASSWORD') | b64encode }}"
      "{{ persistent_mongo_url_key_name }}": "{{ lookup('file', '/keybase/team/'+ keybase_secrets_folder +'/' + persistent_mongo_url_key_name) | b64encode }}"
