
---
# vars file for epfl.phd-assess

openshift_local_images_base: "docker-registry.default.svc:5000/{{ openshift_namespace }}"

app_name: "phd-assess"
svc_name: "{{ app_name }}"
route_name: "{{ app_name }}"

_frontend_hostname_suffix: >-
  {{ openshift_namespace | replace("phd-assess", "") |
  regex_replace("^-", "") }}
frontend_hostname: >-
  {{ "phd-annual-report" if (openshift_namespace == "phd-assess")
  else ("phd-annual-report-" + _frontend_hostname_suffix) }}
frontend_fqdn: "{{ frontend_hostname }}.epfl.ch"

frontend_url: "https://{{ frontend_hostname }}"
zeebe_gateway_servicename: "zeebe-gateway"

phd_assess_meteor_servicename: "phd-assess-meteor"
phd_assess_meteor_image_tag: "{{openshift_image_registry}}/{{openshift_namespace}}/{{phd_assess_meteor_servicename}}:latest"
keybase_secrets_folder: >-
  {{ "epfl_phdassess.test" if ("test" in openshift_namespace)
    else "epfl_phdassess" }}
secret_name: "phd-assess.secrets"
meteor_secret_name: "phd-assess.meteor.secrets"
encryption_key_name: "PHDASSESS_ENCRYPTION_KEY"
websrv_password_key_name: "WEBSRV_PASSWORD"
persistent_mongo_url_key_name: "MONGO_PERSISTENT_URL"
volume_zeebe_name: >-
  {{ "svc1394-svc0166-phd-assess-test-zeebe-partition-app-app" if ("test" in openshift_namespace)
    else "svc0166-" + app_name + "-zeebe-partition-app" }}

phd_assess_meteor_image_name: "phd-assess-meteor"
