# Variables common to multiple roles (a.k.a. “rendezvous” vars) go here.

openshift_image_registry: "os-docker-registry.epfl.ch"
openshift_image_registry_inside: "docker-registry.default.svc:5000"
phd_assess_build_namespace: phd-assess-test

toplevel_state_dir: /srv/esb

esb_ssh_tunnels:
  host: itsphdrepor0001.xaas.epfl.ch
  username: esb-tunnel
  client_keys_dir: "{{ toplevel_state_dir }}/ssh-tunnel/client"
  forward:
    zeebe:
      - name: zeebe-quorum-0
  reverse:
    zeebe:
      - quorum_id: 1
        name: zeebe-quorum-1
        via: 22222
      - quorum_id: 2
        name: zeebe-quorum-2
        via: 22223
    prometheus:
      via: 22223

zeebe_version: '8.2.18'

# The rendezvous port for Zeebe API connections (to use by clients and k8s services)
zeebe_ports:
  # The port of the “Zeebe gateways,” where clients connect:
  api: 26500
  # The port through which gateways reach brokers. Note that despite
  # every gateway having a broker next to it in the same pod, it will
  # not necessarily talk to that one. (Rather, the network coordinates
  # of all brokers are broadcast through the “gossip” mechanism when
  # gateways start up)
  command: 26501
  # The port that brokers use to connect to each other to make the Raft network:
  quorum: 26502

_zeebe_log_level: >-
  {{ "info" if is_test | default(false) else "info" }}

zeebe_env:
  PORT: '{{ zeebe_ports.api | string }}'
  JAVA_OPTS: "{{ '-Xmx2024m' }}"
  ZEEBE_BROKER_NETWORK_MONITORINGAPI_HOST: '0.0.0.0'
  # https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/setting-up-a-cluster/
  ZEEBE_LOG_APPENDER: Stackdriver
  ZEEBE_BROKER_BACKPRESSURE_ALGORITHM: fixed
  ZEEBE_BROKER_BACKPRESSURE_FIXEDLIMIT_LIMIT: '300'
  ZEEBE_BROKER_THREADS_CPUTHREADCOUNT: '1'
  ZEEBE_BROKER_THREADS_IOTHREADCOUNT: '1'
  ZEEBE_BROKER_CLUSTER_CLUSTERNAME: epfl
  ZEEBE_BROKER_CLUSTER_CLUSTERSIZE: "3"
  ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR: "3"
  ZEEBE_LOG_LEVEL: "{{ _zeebe_log_level }}"
  ATOMIX_LOG_LEVEL: "{{ _zeebe_log_level }}"
